spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/vibook_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 9090
  shutdown: graceful
